authentication/urls.py
from django.urls import path
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from authentication.views import email_validation, logout, registration


app_name = 'authentication'

urlpatterns = [
    path('registration', registration, name='registration'),
    path('email-validation', email_validation, name='email-validation'),
    path('login', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('refresh', TokenRefreshView.as_view(), name='token_refresh'),
    path('logout', logout, name='logout'),
]

main/urls.py
from django.urls import path

from main.views import get_country, get_user

app_name = 'main'

urlpatterns = [
    path('location', get_country, name='get_country'),
    path('user', get_user, name='get_user'),
]

pbp_e_03/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('donation', include('donation.urls')),
    path('auth/', include('authentication.urls')),
    path('leaderboard/', include('leaderboard.urls')),
    path('market/', include('market.urls')),
    path('profile/', include('user_profile.urls')),
    path('history/', include('history.urls')),
]

authentication/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, UserManager, BaseUserManager, PermissionsMixin

class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=255, default=None)
    phone = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    email = models.EmailField(max_length=254, unique=True)
    coin_amount = models.IntegerField(default=0)

    is_staff = models.BooleanField(default=False) # a admin user; non super-user
    is_superuser = models.BooleanField(default=False) # a superuser
    
    USERNAME_FIELD =  'email'
    REQUIRED_FIELDS = ['username']

    objects = UserManager()

    def get_name(self):
        return self.username
    
    def get_coin(self):
        return self.coin_amount

authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from authentication.models import User
from phonenumber_field.formfields import PhoneNumberField

class RegistrationForm(UserCreationForm):
    username = forms.CharField(required=True, label="Name", widget=forms.TextInput(attrs={
        'placeholder': "John Doe"
    }))
    phone = PhoneNumberField(region="ID", required=True, label="Phone Number", widget=forms.TextInput(attrs={
        'placeholder': "0858xxxxxxxxx"
    }))
    address = forms.CharField(required=True, label="Address", widget=forms.Textarea(attrs={
        'placeholder': "Tree Street, 27"
    }))
    
    class Meta:
        model = User
        fields = ('username', 'phone', 'address', 'email')
        widgets = {
            'email': forms.EmailInput(attrs={
                'placeholder': "example@mail.com"
            }),
        }
    
    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['password1'].widget = forms.PasswordInput(attrs={'placeholder': "Must have at least 6 characters"})
        self.fields['password2'].widget = forms.PasswordInput(attrs={'placeholder': "Retype your password"})

class LoginForm(forms.Form):
    email = forms.EmailField(required=True, label="Email", widget=forms.EmailInput(attrs={
        'placeholder': "example@mail.com"    
    }))
    password = forms.CharField(required=True, label="Email", widget=forms.PasswordInput(attrs={
        'placeholder': "Must have at least 6 characters"    
    })) 
    remember_me = forms.BooleanField(label="Remember Me", required=False)
    
    class Meta:
        model = User

authentication/views.py
from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from rest_framework.request import Request
from rest_framework import status
from authentication.models import User
from rest_framework_simplejwt.tokens import RefreshToken
from rest_framework.permissions import IsAuthenticated

from authentication.serializers import RegistrationSerializer
from leaderboard.models import UserStatsSummary

# Create your views here.
@api_view(['POST'])
def email_validation(request: Request):
    try:
        email = request.data.get('email')
        is_exist = True
        
        if email is not None:
            user = User.objects.filter(email = email).first()
            
            if user is None:
                is_exist = False

            response = {
                "success": True,
                "content": {
                    "is_exist": is_exist
                },
                "message": "User already exists!" if is_exist else "User not found!",
            }
            return Response(data=response, status=status.HTTP_200_OK)
        else:
            response = {
                "success": False,
                "content": None,
                "message": "Email is required!",
            }
            return Response(data=response, status=status.HTTP_400_BAD_REQUEST)
    except Exception as e:
        response = {
                "success": False,
                "content": None,
                "message": str(e),
            }
        return Response(data=response, status=status.HTTP_500_INTERNAL_SERVER_ERROR) 

@api_view(['POST'])    
def registration(request: Request):
    try:
        serializer = RegistrationSerializer(data=request.data)
    
        if serializer.is_valid():
            user = serializer.save()
            
            userStatsSummary = UserStatsSummary.objects.create(user=user)  
            userStatsSummary.save()
                      
            token = RefreshToken.for_user(user)

            response = {
                "success": True,
                "content": {
                    "refresh": str(token),
                    "access": str(token.access_token)    
                },
                "message": "Successfully registered",
            }
            return Response(data=response, status=status.HTTP_201_CREATED)
        else:
            response = {
                "success": False,
                "content": None,
                "message": "Missing required information!",
            }
            return Response(data=response, status=status.HTTP_400_BAD_REQUEST) 
    except Exception as e:
        response = {
                "success": False,
                "content": None,
                "message": str(e),
            }
        return Response(data=response, status=status.HTTP_500_INTERNAL_SERVER_ERROR) 
    
    
@api_view(['POST'])
@permission_classes([IsAuthenticated])
def logout(request: Request):
    try:
        refresh_token = request.data["refresh"]
        token = RefreshToken(refresh_token)
        token.blacklist()
        
        response = {
                "success": True,
                "content": None,
                "message": "Successfully logged out",
            }

        return Response(data=response, status=status.HTTP_205_RESET_CONTENT)
    except Exception as e:
        response = {
                "success": False,
                "content": None,
                "message": str(e),
            }
        return Response(data=response, status=status.HTTP_500_INTERNAL_SERVER_ERROR) 

authentication/templates/login.html
{% block content %}
<div
  class="flex flex-col items-center justify-center w-full gap-5 p-4 bg-white md:p-6 lg:w-1/4 md:w-1/2 rounded-3xl"
  id="login-modal"
>
  <div class="flex flex-col items-center">
    <h1 class="text-3xl font-bold text-[#56C969]">Login</h1>
    <h2 class="text-lg font-bold">To Start Make an Impact</h2>
  </div>

  <span id="alert" class="hidden w-full px-4 py-2 text-white rounded-xl"></span>

  <form id="login-form" class="flex flex-col w-full gap-5">
    <div class="flex flex-col group">
      <label
        for="id_email"
        class="group-hover:text-[#56C969] group-focus:text-[#56C969]"
        >Email</label
      >
      {{form.email}}
    </div>
    <div class="flex flex-col group">
      <label
        for="id_password"
        class="group-hover:text-[#56C969] group-focus:text-[#56C969]"
        >Password</label
      >
      {{form.password}}
    </div>
    <div class="flex justify-between">
      <label class="flex items-center gap-2">
        {{form.remember_me}} <span>Remember Me</span>
      </label>
    </div>
    <div class="flex w-full gap-5">
      <button id="cancel-login" class="w-1/2 text-white button-secondary">
        Cancel
      </button>
      <button
        type="submit"
        id="submit-login"
        class="w-1/2 text-white button-primary"
      >
        Login
      </button>
    </div>
  </form>
  <div
    id="registration-anchor"
    class="w-full font-bold text-center text-blue-600 cursor-pointer hover:text-blue-800"
  >
    Doesn’t Have any Account?
  </div>
</div>
{% endblock content %}

authentication/templates/registration.html
{% block content %}
<div
  class="flex flex-col items-center gap-5 md:p-6 p-4 md:w-[470px] rounded-3xl bg-white"
>
  <div class="flex flex-col items-center">
    <h1 class="text-3xl font-bold text-[#56C969]">Register</h1>
    <h2 class="text-lg font-bold text-center">
      To Make an Impact to the World
    </h2>
  </div>

  <span
    id="alert"
    class="flex-col hidden w-full px-4 py-2 text-white bg-red-600 rounded-xl"
  ></span>

  <form id="registration-form" class="flex flex-col w-full gap-5">
    <div class="flex flex-col h-[470px] overflow-auto">
      <div class="flex flex-col group">
        <label
          for="id_username"
          class="group-hover:text-[#56C969] group-focus:text-[#56C969]"
          >Name</label
        >
        {{form.username}}
      </div>
      <div class="flex flex-col group">
        <label
          for="id_phone"
          class="group-hover:text-[#56C969] group-focus:text-[#56C969]"
          >Phone</label
        >
        {{form.phone}}
      </div>
      <div class="flex flex-col group">
        <label
          for="id_address"
          class="group-hover:text-[#56C969] group-focus:text-[#56C969]"
          >Address</label
        >
        {{form.address}}
      </div>
      <div class="flex flex-col group">
        <label
          for="id_email"
          class="group-hover:text-[#56C969] group-focus:text-[#56C969]"
          >Email</label
        >
        {{form.email}}
      </div>
      <div class="flex flex-col group">
        <label
          for="id_password1"
          class="group-hover:text-[#56C969] group-focus:text-[#56C969]"
          >Password</label
        >
        {{form.password1}}
      </div>
      <div class="flex flex-col group">
        <label
          for="id_password2"
          class="group-hover:text-[#56C969] group-focus:text-[#56C969]"
          >Password Confirmation</label
        >
        {{form.password2}}
      </div>
    </div>
    <div class="flex w-full gap-5">
      <button
        id="cancel-registration"
        class="w-1/2 text-white button-secondary"
      >
        Cancel
      </button>
      <button
        type="submit"
        id="submit-registration"
        class="w-1/2 text-white button-primary"
      >
        Register
      </button>
    </div>
  </form>
</div>
{% endblock content %}