main/urls.py
from django.urls import path

from main.views import get_country, get_user

app_name = 'main'

urlpatterns = [
    path('location', get_country, name='get_country'),
    path('user', get_user, name='get_user'),
]

pbp_e_03/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('donation', include('donation.urls')),
    path('auth/', include('authentication.urls')),
    path('leaderboard/', include('leaderboard.urls')),
    path('market/', include('market.urls')),
    path('profile/', include('user_profile.urls')),
    path('history/', include('history.urls')),
]

user_profile/urls.py
from django.urls import path

from user_profile.views import index, update_password, update_profile

app_name = 'user_profile'

urlpatterns = [
    path('', index, name='profile'),
    path('update', update_profile, name='update_profile'),
    path('update-password', update_password, name='update_password'),
]

templates/base.html
{% load tailwind_tags %} {% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Generositree</title>

    <!-- import Monsterrat font -->
    <link
      href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&family=Roboto&display=swap"
      rel="stylesheet"
    />

    {% tailwind_css %} {% block meta %} {% endblock meta %}
  </head>

  <body class="relative w-full h-screen">
    <nav class="fixed flex flex-col w-full h-14">
      <div class="flex items-center justify-between w-full px-3 py-2 bg-white">
        <a href="/">
          <img
            src="{% static '/images/GenerosiTree.png' %}"
            class="w-28 md:w-auto"
          />
        </a>
        <div class="items-center hidden gap-6 md:flex">
          <div class="flex gap-4">
            <a href="/" class="font-bold hover:text-[#56C969]">Home</a>
            <a href="/donation" class="font-bold hover:text-[#56C969]"
              >Donation</a
            >
            <a href="/market" class="font-bold hover:text-[#56C969]">Market</a>
          </div>
          {% if user.is_authenticated %}
          <div class="relative">
            <button id="dropdown-btn" class="flex flex-col gap-2">
              <span class="font-bold text-[#56C969]">
                Hello, {{user.get_name }}
              </span>
              <span class="flex items-center gap-2">
                <img src="/static/images/coin.png" />
                <span class="font-bold">{{ user.get_coin }}</span>
              </span>
            </button>
            <div
              id="dropdown"
              class="absolute flex-col hidden w-full gap-2 px-4 py-2 mt-6 bg-white rounded-lg drop-shadow-2xl"
            >
              <a
                href="{% url 'user_profile:profile' %}"
                class="hover:text-[#56C969]"
                >Profile</a
              >
              <div>test</div>
              <button
                id="logout-btn"
                class="font-bold text-left text-red-600 hover:text-red-800"
              >
                Logout
              </button>
            </div>
          </div>
          {% else %}
          <button id="login-btn" class="text-white button-primary">Login</button
          >{% endif %}
        </div>
        <button id="menu-btn" class="group md:hidden">
          <img
            src="{% static '/images/bars.svg' %}"
            class="block group-hover:hidden"
          />
          <img
            src="{% static '/images/bars-green.svg' %}"
            class="hidden group-hover:block"
          />
        </button>
      </div>
      <div
        id="expanded-navbar"
        class="flex-col hidden w-full gap-2 px-3 py-2 bg-white"
      >
        <div class="flex flex-col gap-1">
          <a href="/" class="font-bold hover:text-[#56C969]">Home</a>
          <a href="/donation" class="font-bold hover:text-[#56C969]"
            >Donation</a
          >
          <a href="/market" class="font-bold hover:text-[#56C969]">Market</a>
        </div>
        <button id="login-btn" class="text-white button-primary">Login</button>
      </div>
    </nav>

    <div
      id="modal"
      class="absolute top-0 z-10 flex-col items-center justify-center hidden w-full h-screen gap-4 px-4 bg-black/50"
    ></div>

    {% block content %} {% endblock content %}

    <footer
      class="flex justify-center w-full py-8 font-bold bg-[#56C969] text-white"
    >
      Developed with ❤️ by PBP E 03
    </footer>

    <script src="{% static '/js/base.js' %}"></script>
    {% block script %}{% endblock script %}
  </body>
</html>